/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file mchp_sam_clock_d5x_e5x.h
 * @brief Clock control driver DT-bindings for Microchip devices.
 *
 * This header file defines the macros for clock controllers, which can
 * be used in device tree nodes for configuring and managing clocks on
 * Microchip-based systems.
 */

#ifndef MICROCHIP_MCHP_CLOCK_SAM_D5X_E5X_H_
#define MICROCHIP_MCHP_CLOCK_SAM_D5X_E5X_H_

/** @brief Clocks handled by the CLK peripheral.
 *
 * This has to be in sync with clock_control subsys ids.
 * Do not use 0 for any of the clocks since it is reserved
 * for indicating all clocks in a subsys.
 */

/* OSCCTRL Clock Controller */
#define CLOCK_MCHP_SAM_D5X_E5X_OSCCTRL_XOSC0  1
#define CLOCK_MCHP_SAM_D5X_E5X_OSCCTRL_XOSC1  2
/* OSCCTRL Clock Controller - DFLL */
#define CLOCK_MCHP_SAM_D5X_E5X_OSCCTRL_DFLL   3
/* OSCCTRL Clock Controller - DPLL */
#define CLOCK_MCHP_SAM_D5X_E5X_OSCCTRL_FDPLL0 4
#define CLOCK_MCHP_SAM_D5X_E5X_OSCCTRL_FDPLL1 5

/* OSC32KCTRL Clock Controller */
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_XOSC32K          1
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_XOSC32K_OUT32K   2
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_XOSC32K_OUT1K    3
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_OSCULP32K        4
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_OSCULP32K_OUT32K 5
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_OSCULP32K_OUT1K  6
#define CLOCK_MCHP_SAM_D5X_E5X_OSC32KCTRL_RTC              7

/* GCLK Generator Controller */
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN0  1
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN1  2
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN2  3
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN3  4
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN4  5
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN5  6
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN6  7
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN7  8
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN8  9
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN9  10
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN10 11
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_GEN11 12

/* GCLK Peripheral Clocks which needs GCLK as input */
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_OSCCTRL_DFLL48 13
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_OSCCTRL_FDPLL0 14
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_OSCCTRL_FDPLL1 15
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_OSCCTRL_SLOW   16
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EIC            17
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_FREQM_MSR      18
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_FREQM_REF      19
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM0_CORE   20
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM1_CORE   21
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TC0_TC1        22
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_USB            23
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS0         24
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS1         25
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS2         26
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS3         27
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS4         28
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS5         29
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS6         30
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS7         31
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS8         32
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS9         33
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS10        34
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_EVSYS11        35
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM2_CORE   36
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM3_CORE   37
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TCC0_TCC1      38
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TC2_TC3        39
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_CAN0           40
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_CAN1           41
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TCC2_TCC3      42
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TC4_TC5        43
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_PDEC           44
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_AC             45
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_CCL            46
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM4_CORE   47
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM5_CORE   48
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM6_CORE   49
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SERCOM7_CORE   50
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TCC4           51
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_TC6_TC7        52
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_ADC0           53
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_ADC1           54
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_DAC            55
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_I2S0           56
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_I2S1           57
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SDHC0          58
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_SDHC1          59
#define CLOCK_MCHP_SAM_D5X_E5X_GCLK_CM4_TRACE      60

/* MCLK Controller */
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_CPU 1
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_HS  2

/* MCLK AHB Clocks */
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_HPB0             3
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_HPB1             4
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_HPB2             5
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_HPB3             6
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_DSU              7
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_NVMCTRL          8
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_CMCC             9
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_DMAC             10
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_USB              11
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_PAC              12
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_QSPI             13
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_GMAC             14
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_SDHC0            15
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_SDHC1            16
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_CAN0             17
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_CAN1             18
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_PUKCC            19
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_QSPI_2X          20
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_NVMCTRL_SMEEPROM 21
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_AHB_NVMCTRL_CACHE    22

/* MCLK APBA Clocks */
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_PAC        23
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_PM         24
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_MCLK       25
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_RSTC       26
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_OSCCTRL    27
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_OSC32KCTRL 28
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_SUPC       29
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_GCLK       30
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_WDT        31
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_RTC        32
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_EIC        33
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_FREQM      34
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_SERCOM0    35
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_SERCOM1    36
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_TC0        37
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBA_TC1        38

/* MCLK APBB Clocks */
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_USB     39
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_DSU     40
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_NVMCTRL 41
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_PORT    42
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_EVSYS   43
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_SERCOM2 44
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_SERCOM3 45
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_TCC0    46
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_TCC1    47
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_TC2     48
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_TC3     49
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBB_RAMECC  50

/* MCLK APBC Clocks */
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_GMAC 51
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_TCC2 52
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_TCC3 53
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_TC4  54
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_TC5  55
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_PDEC 56
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_AC   57
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_AES  58
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_TRNG 59
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_ICM  60
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_QSPI 61
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBC_CCL  62

/* MCLK APBD Clocks */
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_SERCOM4 63
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_SERCOM5 64
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_SERCOM6 65
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_SERCOM7 66
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_TCC4    67
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_TC6     68
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_TC7     69
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_ADC0    70
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_ADC1    71
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_DAC     72
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_I2S     73
#define CLOCK_MCHP_SAM_D5X_E5X_MCLK_APBD_PCC     74

#endif /* MICROCHIP_MCHP_CLOCK_SAM_D5X_E5X_H_ */
